name: Test and package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Test & Coverage
        run: |
              cargo install cargo-llvm-cov
              cargo llvm-cov
      - name: Package .deb file
        run: |
              cargo install cargo-deb
              cargo deb --deb-revision ${{ github.RUN_NUMBER }}
              echo "DEB_FILE=$(find . -name "*.deb")" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v5
        with:
          path: ${{ env.DEB_FILE }}
          name: .deb file
      - name: Create container
        run: |
              cp ${{ env.DEB_FILE }} ./daily_server.deb
              docker build -f deploy/Dockerfile -t "daily_server:${{ github.sha }}" .
