name: Test and package

on: [push]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Test & Coverage
        run: |
              cargo install cargo-llvm-cov
              cargo llvm-cov
      - name: Package .deb file
        run: |
              cargo install cargo-deb
              cargo deb --deb-revision ${{ github.RUN_NUMBER }}
              echo "DEB_FILE=$(find . -name "*.deb")" >> $GITHUB_ENV
              cp "$(find . -name "*.deb")" daily_server.deb
      - uses: actions/upload-artifact@v5
        with:
          path: ${{ env.DEB_FILE }}
          name: .deb file
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push container
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: deploy/Dockerfile
          tags: |
            ghcr.io/paolomazzon/daily_server:latest
            ghcr.io/paolomazzon/daily_server:${{ github.sha }}